/***************************************************************************************
 * Decompiled by Ate47 and Edited by SyndiShanX
 * Script: autogenerated\luielems\cp\cp_test_journalist1_uni_download_hack_luielem.gsc
***************************************************************************************/

#using scripts\core_common\clientfield_shared;
#using scripts\core_common\lui_shared;
#namespace cp_test_journalist1_uni_download_hack_luielem;
class class_b201538a: cluielem {
  var var_bf9c8c95;
  var var_d5213cbb;

  function open(player, flags = 0) {
    cluielem::open_luielem(player, flags);
  }

  function close(player) {
    cluielem::close_luielem(player);
  }

  function setup_clientfields() {
    cluielem::setup_clientfields("cp_test_journalist1_uni_download_hack_luielem");
    cluielem::add_clientfield("_state", 1, 2, "int");
    cluielem::add_clientfield("download_progress", 1, 7, "float");
  }

  function function_97bf49cb(player, value) {
    player clientfield::function_9bf78ef8(var_d5213cbb, var_bf9c8c95, "download_progress", value);
  }

  function set_state(player, state_name) {
    if(#"defaultstate" == state_name) {
      player clientfield::function_9bf78ef8(var_d5213cbb, var_bf9c8c95, "_state", 0);
      return;
    }

    if(#"paused" == state_name) {
      player clientfield::function_9bf78ef8(var_d5213cbb, var_bf9c8c95, "_state", 1);
      return;
    }

    if(#"finished" == state_name) {
      player clientfield::function_9bf78ef8(var_d5213cbb, var_bf9c8c95, "_state", 2);
      return;
    }

    assertmsg("<dev string:x38>");
  }
}

function register() {
  elem = new class_b201538a();
  [[elem]] - > setup_clientfields();
  return elem;
}

function open(player, flags = 0) {
  [[self]] - > open(player, flags);
}

function close(player) {
  [[self]] - > close(player);
}

function is_open(player) {
  return [[self]] - > function_7bfd10e6(player);
}

function set_state(player, state_name) {
  [[self]] - > set_state(player, state_name);
}

function function_97bf49cb(player, value) {
  [[self]] - > function_97bf49cb(player, value);
}