/***********************************************
 * Decompiled by Ate47 and Edited by SyndiShanX
 * Script: hashed\script_71cdde87963901ec.csc
***********************************************/

#using scripts\autogenerated\luielems\sr_objective_reward_menu;
#using scripts\core_common\system_shared;
#namespace namespace_cda50904;

function private autoexec __init__system__() {
  system::register(#"hash_57d1b71f57332413", &preinit, undefined, undefined, undefined);
}

function private preinit() {}